### ISSUE TITLE
Can't kill ennemies

### ISSUE THREAD

**Issue by Vortal4** [NgGH707/NgGH-Magic-Origins-Mod#2] opened 2022-02-05 16:52 UTC
When I create a new game and start a fight, I hit an enemies until they dies but they continue to fight and do damage even if they are at zero HP. When I remove mod_nggh_magic_origins_legends_3.0.0.2_op_edition, the enemies die normally and everything work fine. It didn't do that when I was using your past version.
Here are the installed mods :
mod_18bros.zip-41-6-1598222895
mod_EIMO_Legends-239-8-7-1637151630
mod_legends_beta_15.0.1.24-60-15-0-1-24-1637433066
mod_legends_breditor-294-3-3-1633856776
mod_stronghold-324-1-1a-1640853205

**Comment by NgGH707** [comment] 2022-02-06 02:18
It will be great if you can provide a log too.

Your log is usually found in: C:\Users\YourName\Documents\Battle Brothers\log.html
The log is constantly updated during game and is reset each time you open the game.

**Comment by Vortal4** [comment] 2022-02-06 02:25
`Battle Brothers 1.4.0.49
12:10:50
Platform
Setting video mode
12:10:50
Platform
Finished setting video mode
12:10:50
Core
Using write path: C:\Users\tdrin\Documents\Battle Brothers
12:10:50
Core
Initializing Resource Manager
12:10:50
Core
Initializing Input Manager
12:10:50
Core
Initializing Render Manager
12:10:50
Renderer
Allocated Renderbuffer in excess of 3072kb.
12:10:50
Renderer
Vendor: NVIDIA Corporation
12:10:50
Renderer
Device: NVIDIA GeForce GTX 1070/PCIe/SSE2
12:10:50
Renderer
Version: 4.6.0 NVIDIA 511.65
12:10:50
Renderer
Shader Version: 4.60 NVIDIA
12:10:50
Renderer
Framebuffer Support: Yes
12:10:50
Core
Initializing Sound Manager
12:10:50
Core
Initializing Scene Manager
12:10:50
Resource
Unloading: shaders/solid.vs
12:10:50
Resource
Unloading: shaders/solid_pass0.fs
12:10:50
Resource
Unloading: shaders/simple.vs
12:10:50
Resource
Unloading: shaders/simple.fs
12:10:50
Resource
Unloading: shaders/sprite.vs
12:10:50
Resource
Unloading: shaders/sprite.fs
12:10:50
Resource
Unloading: shaders/sprite_dof.vs
12:10:50
Resource
Unloading: shaders/sprite_dof.fs
12:10:50
Core
Initializing Script Manager
12:10:50
Core
Initializing UI Manager
12:10:50
Resource
Unloading: shaders/ui.vs
12:10:50
Resource
Unloading: shaders/ui.fs
12:10:50
Core
Initializing Input Action Manager
12:10:50
Core
Initializing State Manager
12:10:50
Core
Initializing Persistence Manager
12:10:50
Resource
Unloading: brushes/debug.brush
12:10:50
Resource
Unloading: brushes/detail.brush
12:10:50
Resource
Unloading: brushes/effects_0.brush
12:10:50
Resource
Unloading: brushes/entity_0.brush
12:10:50
Resource
Unloading: brushes/entity_1.brush
12:10:50
Resource
Unloading: brushes/entity_2.brush
12:10:50
Resource
Unloading: brushes/entity_3.brush
12:10:50
Resource
Unloading: brushes/entity_4.brush
12:10:50
Resource
Unloading: brushes/entity_5.brush
12:10:50
Resource
Unloading: brushes/entity_6.brush
12:10:50
Resource
Unloading: brushes/entity_blood.brush
12:10:50
Resource
Unloading: brushes/entity_icons.brush
12:10:50
Resource
Unloading: brushes/entity_mc.brush
12:10:50
Resource
Unloading: brushes/legend_armor_0.brush
12:10:50
Resource
Unloading: brushes/legend_armor_1.brush
12:10:50
Resource
Unloading: brushes/legend_characters.brush
12:10:50
Resource
Unloading: brushes/legend_enemies.brush
12:10:50
Resource
Unloading: brushes/legend_helmets.brush
12:10:50
Resource
Unloading: brushes/legend_helmets_0.brush
12:10:50
Resource
Unloading: brushes/legend_helmets_1.brush
12:10:50
Resource
Unloading: brushes/legend_helmets_2.brush
12:10:50
Resource
Unloading: brushes/legend_horses.brush
12:10:50
Resource
Unloading: brushes/legend_objects.brush
12:10:50
Resource
Unloading: brushes/legend_weapons.brush
12:10:50
Resource
Unloading: brushes/legend_world.brush
12:10:50
Resource
Unloading: brushes/legends_ui.brush
12:10:50
Resource
Unloading: brushes/named_staves.brush
12:10:50
Resource
Unloading: brushes/object_0.brush
12:10:50
Resource
Unloading: brushes/object_1.brush
12:10:50
Resource
Unloading: brushes/orientation_overlay.brush
12:10:50
Resource
Unloading: brushes/quotes.brush
12:10:50
Resource
Unloading: brushes/stronghold_worldmap.brush
12:10:50
Resource
Unloading: brushes/terrain.brush
12:10:50
Resource
Unloading: brushes/transitions.brush
12:10:50
Resource
Unloading: brushes/ui.brush
12:10:50
Resource
Unloading: brushes/ui_mc.brush
12:10:50
Resource
Unloading: brushes/world_decals.brush
12:10:50
Resource
Unloading: brushes/world_detail.brush
12:10:50
Resource
Unloading: brushes/world_detail_1.brush
12:10:50
Resource
Unloading: brushes/world_entity_0.brush
12:10:50
Resource
Unloading: brushes/world_settlement.brush
12:10:50
Resource
Unloading: brushes/world_special.brush
12:10:50
Resource
Unloading: brushes/world_tiles.brush
12:10:50
Resource
Unloading: brushes/world_weather.brush
12:10:50
IO
Unexpected file or directory found: mod_EIMO_Legends-239-8-7-1637151630.zip
12:10:50
IO
Unexpected file or directory found: mod_ends_uncapped_company_25_16-230-1-1-1598292993.zip
12:10:50
IO
Unexpected file or directory found: mod_legends_beta_15.0.1.24-60-15-0-1-24-1637433066.zip
12:10:50
IO
Unexpected file or directory found: mod_legends_breditor-294-3-3-1633856776.zip
12:10:50
IO
Unexpected file or directory found: mod_nggh_magic_origins_legends_3.0.0.1_op_edition.zip
12:10:50
IO
Unexpected file or directory found: mod_stronghold-324-1-1a-1640853205.zip
12:10:50
IO
The game uses modified files or files that are not part of the official release. If you encounter any issues, please first remove any mods and try again before contacting support.
12:10:50
Resource
Unloading: shaders/fow.vs
12:10:50
Resource
Unloading: shaders/fow.fs
12:10:50
Texture
Texture "gfx/fow.png" (ID: 5) took up approximately 16384kb in video memory.
12:10:50
Resource
Unloading: shaders/water.vs
12:10:50
Resource
Unloading: shaders/water.fs
12:10:50
Texture
Texture "gfx/water.png" (ID: 6) took up approximately 16384kb in video memory.
12:10:51
Texture
Texture "gfx/world_tiles.png" (ID: 7) took up approximately 43680kb in video memory.
12:10:51
Texture
Texture "gfx/world_special.png" (ID: 8) took up approximately 256kb in video memory.
12:10:51
Texture
Texture "gfx/terrain.png" (ID: 9) took up approximately 10912kb in video memory.
12:10:51
Texture
Texture "gfx/transitions.png" (ID: 10) took up approximately 5456kb in video memory.
12:10:51
Resource
Parsed Resource Package "preload/on_start.txt" with 8 items.
12:10:51
Resource
Started loading Resource Package "preload/on_start.txt".
12:10:51
Texture
Compressed texture "gfx/effects_0.png" from 16384kb to 4096kb.
12:10:51
Texture
Compressed texture "gfx/world_weather.png" from 32768kb to 8192kb.
12:10:51
Texture
Texture "gfx/ui.png" (ID: 13) took up approximately 10922kb in video memory.
12:10:51
Texture
Texture "gfx/ui_mc.png" (ID: 14) took up approximately 5461kb in video memory.
12:10:51
Texture
Texture "gfx/entity_mc.png" (ID: 15) took up approximately 5461kb in video memory.
12:10:51
Texture
Texture "gfx/quotes.png" (ID: 16) took up approximately 5461kb in video memory.
12:10:51
Texture
Texture "gfx/fonts/cinzel_bold_20.png" (ID: 17) took up approximately 512kb in video memory.
12:10:51
Texture
Texture "gfx/fonts/cinzel_bold_100.png" (ID: 18) took up approximately 8192kb in video memory.
12:10:52
SQ
Legends Mod Version 15.0.1.24
12:10:52
SQ
mod_hooks: Redirecting core functions
12:10:52
SQ
mod_hooks: mod_hooks (modding script hooks) version 21.1 registered.
12:10:52
Script Error
the index 'FreeCompanyLeader' does not exist
Function:
main -> scripts/!mods_preload/!config/mc_necro_corpse.nut : 6
Variables:
gt = Table, vargv = Array, this = Table
Function:
unknown -> NATIVE : -1
Function:
main -> scripts/preload.nut : 62
Variables:
@ITERATOR@ = 6, scriptFile = scripts/!mods_preload/!config/mc_necro_corpse, @INDEX@ = 5, scriptFiles = Array, dlcInitScriptFiles = Array, configScriptFiles = Array, priorityScriptFiles = Array, scriptsDLCInitPath = scripts/dlc/, scriptsConfigPath = scripts/config/, scriptsPath = scripts/, gt = Table, vargv = Array, this = Table
12:10:52
Script
Failed to execute script file "scripts/!mods_preload/!config/mc_necro_corpse.cnut". Reason: "the index 'FreeCompanyLeader' does not exist".
12:10:52
SQ
mod_hooks: mod_legends (Legends Mod) version 15 registered.
12:10:52
SQ
mod_hooks: mod_mediumArmorRework (Medium Armor Rework (MAR) 1.4.8) version 1.4 registered.
12:10:52
SQ
mod_hooks: mod_EIMO_legends (End's Inventory Management Overhaul Legends) version 8 registered.
12:10:52
SQ
mod_hooks: mod_smart_loot_EIMO_Legends (Smart Loot integrated into EIMO) version 2.3 registered.
12:10:52
SQ
mod_hooks: mod_breditor (Breditor) version 1 registered.
12:10:52
SQ
mod_hooks: EndsUncappedCompany version 1.1 registered.
12:10:52
SQ
mod_hooks: mod_nggh_magic_concept (It's magic) version 2.2 registered.
12:10:52
SQ
mod_hooks: mod_nggh_assets version 2.2 registered.
12:10:52
SQ
mod_hooks: mod_nggh_skills version 2.2 registered.
12:10:52
SQ
mod_hooks: mod_nggh_accessory_dog version 2.2 registered.
12:10:52
SQ
mod_hooks: mod_MSU (Modding Standards and Utils 0.6.24) version 1 registered.
12:10:52
SQ
mod_hooks: mod_stronghold version 1 registered.
12:10:52
SQ
mod_hooks: Executing queued script for mod_nggh_skills.
12:10:52
SQ
mod_hooks: Executing queued script for mod_EIMO_legends (End's Inventory Management Overhaul Legends).
12:10:52
SQ
mod_hooks: Executing queued script for mod_breditor (Breditor).
12:10:52
SQ
mod_hooks: Executing queued script for EndsUncappedCompany.
12:10:52
SQ
mod_hooks: Executing queued script for mod_nggh_assets.
12:10:52
SQ
mod_hooks: Executing queued script for mod_nggh_accessory_dog.
12:10:52
SQ
mod_hooks: Executing queued script for mod_stronghold.
12:10:52
SQ
mod_hooks: Executing queued script for mod_MSU (Modding Standards and Utils 0.6.24).
12:10:52
SQ
mod_hooks: Executing queued script for mod_smart_loot_EIMO_Legends (Smart Loot integrated into EIMO).
12:10:52
SQ
mod_hooks: Executing queued script for mod_legends (Legends Mod).
12:10:52
SQ
mod_hooks: Executing queued script for mod_mediumArmorRework (Medium Armor Rework (MAR) 1.4.8).
12:10:52
SQ
mod_hooks: Executing queued script for mod_nggh_magic_concept (It's magic).
12:10:55
UI
Screen 'RootScreen' successfully registered.
12:10:55
UI
Screen 'ConsoleScreen' successfully registered.
12:10:55
UI
Screen 'LoadingScreen' successfully registered.
12:10:55
UI
Screen 'TooltipScreen' successfully registered.
12:10:55
UI
Screen 'DialogScreen' successfully registered.
12:10:55
UI
Screen 'TacticalScreen' successfully registered.
12:10:55
UI
Screen 'TacticalCombatResultScreen' successfully registered.
12:10:55
UI
Screen 'TacticalDialogScreen' successfully registered.
12:10:55
UI
Screen 'WorldScreen' successfully registered.
12:10:55
UI
Screen 'WorldTownScreen' successfully registered.
12:10:55
UI
Screen 'WorldGameFinishScreen' successfully registered.
12:10:55
UI
Screen 'WorldEventPopupScreen' successfully registered.
12:10:55
UI
Screen 'WorldEventScreen' successfully registered.
12:10:55
UI
Screen 'WorldCombatDialog' successfully registered.
12:10:55
UI
Screen 'WorldRelationsScreen' successfully registered.
12:10:55
UI
Screen 'WorldObituaryScreen' successfully registered.
12:10:55
UI
Screen 'WorldCampfireScreen' successfully registered.
12:10:55
UI
Screen 'MainMenuScreen' successfully registered.
12:10:55
UI
Screen 'WorldMenuScreen' successfully registered.
12:10:55
UI
Screen 'TacticalMenuScreen' successfully registered.
12:10:55
UI
Screen 'WorldCharacterScreen' successfully registered.
12:10:55
UI
Screen 'TacticalCharacterScreen' successfully registered.
12:10:55
UI
Screen 'CampScreen' successfully registered.
12:10:55
UI
Screen 'WorldBreditorScreen' successfully registered.
12:10:56
SQ
RootState::onShow()
12:10:56
Resource
Parsed Resource Package "preload/on_running.txt" with 43 items.
12:10:56
Resource
Started loading Resource Package "preload/on_running.txt".
12:10:56
Texture
Texture "gfx/entity_blood.png" (ID: 19) took up approximately 5461kb in video memory.
12:10:56
Script
VM collected 18 object(s) and deleted them.
12:10:56
Texture
Texture "gfx/legend_characters.png" (ID: 20) took up approximately 21845kb in video memory.
12:10:56
Texture
Texture "gfx/legends_ui.png" (ID: 24) took up approximately 2730kb in video memory.
12:10:56
UI
Screen 'CampScreenButcherDialogModule' successfully registered.
12:10:57
Texture
Texture "gfx/legend_world.png" (ID: 47) took up approximately 87381kb in video memory.
12:10:57
Texture
Texture "gfx/legend_weapons.png" (ID: 48) took up approximately 43690kb in video memory.
12:10:57
Texture
Texture "gfx/entity_0.png" (ID: 49) took up approximately 43690kb in video memory.
12:10:57
Texture
Texture "gfx/entity_3.png" (ID: 50) took up approximately 10922kb in video memory.
12:10:57
Texture
Texture "gfx/entity_icons.png" (ID: 52) took up approximately 43690kb in video memory.
12:10:58
Texture
Texture "gfx/world_detail.png" (ID: 53) took up approximately 43690kb in video memory.
12:10:58
Texture
Texture "gfx/world_entity_0.png" (ID: 54) took up approximately 21845kb in video memory.
12:10:58
Texture
Texture "gfx/world_settlement.png" (ID: 64) took up approximately 43690kb in video memory.
12:10:58
Texture
Texture "gfx/world_decals.png" (ID: 69) took up approximately 10920kb in video memory.
12:11:09
SQ
WaterConnectivity = 38
12:11:09
SQ
GreaterEvil = 0
12:11:09
SQ
LegendAllBlueprints = false
12:11:09
SQ
LegendCampUnlock = true
12:11:09
SQ
LandMassMult = 50
12:11:09
SQ
Width = 140
12:11:09
SQ
AllTradeLocations = false
12:11:09
SQ
Ironman = false
12:11:09
SQ
BudgetDifficulty = 0
12:11:09
SQ
EconomicDifficulty = 0
12:11:09
SQ
ForestsMult = 0.5
12:11:09
SQ
NumFactions = 3
12:11:09
SQ
LegendBleedKiller = true
12:11:09
SQ
FOW = true
12:11:09
SQ
StackCitadels = false
12:11:09
SQ
Snowline = 0.85
12:11:09
SQ
LegendMagic = false
12:11:09
SQ
LegendTherian = false
12:11:09
SQ
Seed = UKMORNMMBL
12:11:09
SQ
Name = Battle Brothers
12:11:09
SQ
MinLandToWaterRatio = 1.7
12:11:09
SQ
Height = 170
12:11:09
SQ
LegendLocationScaling = true
12:11:09
SQ
LegendIsHelmet = 1
12:11:09
SQ
LegendWorldEconomy = true
12:11:09
SQ
NumSettlements = 27
12:11:09
SQ
PermanentDestruction = false
12:11:09
SQ
LegendArmor = true
12:11:09
SQ
LegendRelationship = false
12:11:09
SQ
LegendRecruitScaling = true
12:11:09
SQ
LegendPerkTrees = true
12:11:09
SQ
LegendItemScaling = true
12:11:09
SQ
Autosave = false
12:11:09
SQ
Difficulty = 0
12:11:09
SQ
Debug = false
12:11:09
SQ
StartingScenario = (table : 0x22758F38)
12:11:09
SQ
LegendGenderEquality = 0
12:11:09
SQ
MountainsMult = 0.5
12:11:09
SQ
Banner = banner_16
12:11:09
SQ
SwampsMult = 0.5
12:11:09
SQ
ExplorationMode = true
12:11:09
SQ
Creating tournament event
12:11:09
SQ
Generating world with following settings...
12:11:09
SQ
Snowline : 0.85
12:11:09
SQ
MinDesertTiles : 2000
12:11:09
SQ
WaterConnectivity : 38
12:11:09
SQ
MinLandToWaterRatio : 1.6
12:11:09
SQ
Vision : 500
12:11:09
SQ
SizeY : 170
12:11:09
SQ
LandMassMult : 1.5
12:11:09
SQ
SizeX : 140
12:11:09
SQ
Building land and sea...
12:11:09
SQ
Land Ocean ratio6.19251 >= 1.6 :: Land :20491 Ocean:3309
12:11:11
SQ
Desert tiles 2493 >= 2000
12:11:11
SQ
World accepted.
12:11:11
SQ
Spacing terrain...
12:11:12
Texture
Texture "gfx/world_detail_1.png" (ID: 23) took up approximately 10922kb in video memory.
12:11:13
SQ
Building settlements...
12:11:13
SQ
Created 31 settlements.
12:11:13
SQ
Building roads...
12:11:14
SQ
Building additional roads...
12:11:14
SQ
Road Brush undefined (1)!
12:11:14
SceneManager
Unknown Brush requested: undefined road brush
12:11:14
SQ
Road Brush undefined (1)!
12:11:14
SceneManager
Unknown Brush requested: undefined road brush
12:11:14
SQ
Road Brush undefined (1)!
12:11:14
SceneManager
Unknown Brush requested: undefined road brush
12:11:14
SQ
Building regions...
12:11:14
SQ
Found 709 separate regions.
12:11:15
SQ
Creating final 57 regions...
12:11:15
SQ
Placing abandoned fortresses...
12:11:15
Texture
Texture "gfx/legend_armor_0.png" (ID: 99) took up approximately 87381kb in video memory.
12:11:16
Texture
Texture "gfx/legend_helmets_2.png" (ID: 100) took up approximately 87381kb in video memory.
12:11:16
Texture
Texture "gfx/legend_helmets_0.png" (ID: 101) took up approximately 87381kb in video memory.
12:11:16
Texture
Texture "gfx/entity_6.png" (ID: 102) took up approximately 10922kb in video memory.
12:11:17
Texture
Texture "gfx/legend_helmets_1.png" (ID: 103) took up approximately 87381kb in video memory.
12:11:17
SQ
Running simulation for 2000 cycles...
12:11:18
SQ
Built Legends Ancient Mastaba location
12:11:18
SQ
Built Legends Tournament location
12:11:18
SQ
Done placing all unique locations.
12:11:18
SQ
Done placing all unique locations.
12:11:18
SQ
Done placing all unique locations.
12:11:18
SQ
Done placing all unique locations.
12:11:18
SQ
Done placing all unique locations.
12:11:25
Resource
Unloading: music/title.ogg
12:11:27
SQ
Location entered: Deichstadt
12:11:31
Resource
Unloading: music/worldmap_02.ogg
12:11:31
SQ
contract activated: Return Item (id: 30)
12:11:36
Resource
Unloading: music/city_02.ogg
12:11:43
SQ
Save campaign: autosave
12:11:43
Scene
Finished saving scene.
12:11:43
SQ
WorldState::onHide
12:11:43
SQ
initMap
12:11:43
Texture
Texture "gfx/detail.png" (ID: 220) took up approximately 10922kb in video memory.
12:11:43
Texture
Texture "gfx/object_0.png" (ID: 274) took up approximately 21845kb in video memory.
12:11:43
TacticalScene
Spawned Entity type "scripts/entity/tactical/enemies/bandit_rabble_poacher" at (20,5).
12:11:43
TacticalScene
Spawned Entity type "scripts/entity/tactical/enemies/bandit_rabble_poacher" at (20,6).
12:11:43
TacticalScene
Spawned Entity type "scripts/entity/tactical/enemies/bandit_rabble" at (19,6).
12:11:43
TacticalScene
Spawned Entity type "scripts/entity/tactical/enemies/bandit_rabble" at (19,7).
12:11:43
TacticalScene
Spawned Entity type "scripts/entity/tactical/enemies/bandit_rabble_poacher" at (20,4).
12:11:43
SQ
INFO: Next round issued: 1
12:11:43
Resource
Started loading Resource Package "Temporary Tactical Resources".
12:11:43
SQ
Turn started for Bandit Rabble
12:11:44
SQ
Turn started for Bandit Rabble Poacher
12:11:45
SQ
Bandit Rabble Poacher uses skill Sling Stone
12:11:46
SQ
Turn started for Bandit Rabble Poacher
12:11:47
Resource
Unloading: music/worldmap_10.ogg
12:11:47
SQ
Bandit Rabble Poacher uses skill Quick Shot
12:11:49
SQ
Turn started for Waelram
12:11:51
SQ
[Waelram] executes skill [Shoot Bolt] on target [Bandit Rabble]
12:11:51
SQ
Waelram uses skill Shoot Bolt
12:11:52
SQ
[Waelram] executes skill [Reload] on target [Waelram]
12:11:52
SQ
Waelram uses skill Reload
12:11:53
SQ
Turn started for Bandit Rabble Poacher
12:11:54
SQ
Bandit Rabble Poacher uses skill Sling Stone
12:11:55
SQ
Turn started for Bandit Rabble
12:11:55
Script
VM collected 15612 object(s) and deleted them.
12:11:56
SQ
Turn started for Henneke
12:12:00
SQ
[Henneke] executes skill [Split Man] on target [Bandit Rabble]
12:12:00
SQ
Henneke uses skill Split Man
12:12:00
SQ
Turn started for Witta
12:12:02
SQ
[Witta] executes skill [Thrust] on target [Bandit Rabble]
12:12:02
SQ
Witta uses skill Thrust
12:12:02
SQ
Bandit Rabble has died.
12:12:02
Script Error
the index 'Necro' does not exist
Function:
setUpAsLootInBattle -> scripts/items/corpses/corpse_item.nut : 446
Variables:
isChampion = False, _fatalityType = 0, _corpse = Table, _type = 106, _entity = Table, this = Table
Function:
-> scripts/!mods_preload/mod_nggh_hexen_origin_actor_and_entity.nut : 41
Variables:
ws_onDeath = Function, corpse = Table, isTail = False, self = Table, _fatalityType = 0, _tile = Instance, _skill = Table, _killer = Table, this = Table
Function:
onDeath -> D:\SteamLibrary\steamapps\common\Battle Brothers\data\scripts\entity\tactical\human.nut : 490
Variables:
flip = False, appearance = Table, isResurrectable = True, _fatalityType = 0, _tile = Instance, _skill = Table, _killer = Table, this = Table
Function:
-> D:\SteamLibrary\steamapps\common\Battle Brothers\data\scripts\!mods_preload\mod_actor.nut : 993
Variables:
tile = Instance, myTile = Instance, isReallyDead = True, _silent = False, _fatalityType = 0, _skill = Table, _killer = Table, this = Table
Function:
onDamageReceived -> scripts/entity/tactical/actor.nut : 1294
Variables:
fatalityType = 0, damage = 42, armorDamage = 0, armor = 0, dmgMult = 1, p = Table, _hitInfo = Table, _skill = Table, _attacker = Table, this = Table
Function:
onDamageReceived -> D:\SteamLibrary\steamapps\common\Battle Brothers\data\scripts\entity\tactical\human.nut : 780
Variables:
_hitInfo = Table, _skill = Table, _attacker = Instance, this = Table
Function:
onScheduledTargetHit -> D:\SteamLibrary\steamapps\common\Battle Brothers\data\scripts\skills\skill.nut : 2407
Variables:
hasArmorHitSound = False, pos = Instance, hitInfo = Table, injuries = Array, damageDirect = 0.25, damageArmor = 27, damageRegular = 29, damageMult = 1, bodyPartDamageMult = 1.5, bodyPart = 1, partHit = 9, _info = Table, this = Table
Function:
attackEntity -> D:\SteamLibrary\steamapps\common\Battle Brothers\data\scripts\skills\skill.nut : 2120
Variables:
info = Table, isHit = True, r = 87, shield = Null, shieldBonus = 0, skill = 82, toHit = 87, distanceToTarget = 1, levelDifference = 0, defense = -5, defenderProperties = Table, astray = False, userTile = Instance, properties = Table, _allowDiversion = True, _targetEntity = Table, _user = Instance, this = Table
Function:
-> D:\SteamLibrary\steamapps\common\Battle Brothers\data\scripts\!mods_preload\msu_mod_skill.nut : 217
Variables:
use = Function, targetEntity = Table, container = Instance, _forFree = False, _targetTile = Instance, this = Table
Function:
-> D:\SteamLibrary\steamapps\common\Battle Brothers\data\scripts\!mods_preload\mod_tactical_state.nut : 579
Variables:
skill = Table, _targetTile = Instance, _activeEntity = Table, this = Table
Function:
setActionStateByMouseEvent -> scripts/states/tactical_state.nut : 1034
Variables:
tile = Instance, activeEntity = Table, _mouseEvent = Instance, this = Table
12:12:08
SQ
INFO: Next round issued: 2
12:12:09
SQ
Turn started for Bandit Rabble Poacher
12:12:10
SQ
Bandit Rabble Poacher uses skill Sling Stone
12:12:11
SQ
Bandit Rabble Poacher uses skill Sling Stone
12:12:12
SQ
Turn started for Bandit Rabble Poacher
12:12:13
SQ
Bandit Rabble Poacher uses skill Quick Shot
12:12:13
SQ
Bandit Rabble Poacher uses skill Quick Shot
12:12:14
SQ
Turn started for Bandit Rabble Poacher
12:12:16
SQ
Bandit Rabble Poacher uses skill Sling Stone
12:12:18
SQ
Turn started for Bandit Rabble
12:12:19
SQ
Bandit Rabble uses skill Hand-to-Hand Attack
12:12:19
SQ
Bandit Rabble uses skill Hand-to-Hand Attack
12:12:21
SQ
Turn started for Bandit Rabble
12:12:22
SQ
Bandit Rabble uses skill Impale
12:12:23
SQ
Turn started for Waelram
12:12:30
SQ
[Waelram] executes skill [Shoot Bolt] on target [Bandit Rabble]
12:12:30
SQ
Waelram uses skill Shoot Bolt
12:12:30
SQ
Bandit Rabble has died.
12:12:30
Script Error
the index 'Necro' does not exist
Function:
setUpAsLootInBattle -> scripts/items/corpses/corpse_item.nut : 446
Variables:
isChampion = False, _fatalityType = 0, _corpse = Table, _type = 106, _entity = Table, this = Table
Function:
-> scripts/!mods_preload/mod_nggh_hexen_origin_actor_and_entity.nut : 41
Variables:
ws_onDeath = Function, corpse = Table, isTail = False, self = Table, _fatalityType = 0, _tile = Instance, _skill = Table, _killer = Table, this = Table
Function:
onDeath -> D:\SteamLibrary\steamapps\common\Battle Brothers\data\scripts\entity\tactical\human.nut : 490
Variables:
flip = False, appearance = Table, isResurrectable = True, _fatalityType = 0, _tile = Instance, _skill = Table, _killer = Table, this = Table
Function:
-> D:\SteamLibrary\steamapps\common\Battle Brothers\data\scripts\!mods_preload\mod_actor.nut : 993
Variables:
tile = Instance, myTile = Instance, isReallyDead = True, _silent = False, _fatalityType = 0, _skill = Table, _killer = Table, this = Table
Function:
onDamageReceived -> scripts/entity/tactical/actor.nut : 1294
Variables:
fatalityType = 0, damage = 69, armorDamage = 0, armor = 0, dmgMult = 1, p = Table, _hitInfo = Table, _skill = Table, _attacker = Table, this = Table
Function:
onDamageReceived -> D:\SteamLibrary\steamapps\common\Battle Brothers\data\scripts\entity\tactical\human.nut : 780
Variables:
_hitInfo = Table, _skill = Table, _attacker = Instance, this = Table
Function:
onScheduledTargetHit -> D:\SteamLibrary\steamapps\common\Battle Brothers\data\scripts\skills\skill.nut : 2407
Variables:
hasArmorHitSound = False, pos = Instance, hitInfo = Table, injuries = Array, damageDirect = 0.5, damageArmor = 26, damageRegular = 46, damageMult = 1, bodyPartDamageMult = 1.5, bodyPart = 1, partHit = 22, _info = Table, this = Table
12:12:31
SQ
[Waelram] executes skill [Reload] on target [Waelram]
12:12:31
SQ
Waelram uses skill Reload
12:12:33
SQ
Turn started for Henneke
12:12:35
SQ
Turn started for Witta
12:12:39
Core
Shutting down engine core.`

**Comment by Vortal4** [comment] 2022-02-06 02:26
[https://files.fm/down.php?i=ndk5s2nnb](url)

**Comment by NgGH707** [comment] 2022-02-06 03:23
You do know that you can drop that log in here, right?
No need to copy paste the entire text

**Comment by NgGH707** [comment] 2022-02-06 03:27
Pretty sure the issue is fixed in build 3.0.0.3

**Comment by Vortal4** [comment] 2022-02-06 03:37
- [ ]

**Comment by Vortal4** [comment] 2022-02-06 03:37
[log.zip](https://github.com/NgGH707/NgGH-Magic-Origins-Mod/files/8009364/log.zip)

**Comment by Vortal4** [comment] 2022-02-06 03:44
It's still doing it even after the 3.0.0.3, each time I create a new game and even if I reinstall the game entirely.
[log.zip](https://github.com/NgGH707/NgGH-Magic-Origins-Mod/files/8009371/log.zip)

**Comment by NgGH707** [comment] 2022-02-06 03:46
please resend the log

**Comment by Vortal4** [comment] 2022-02-06 03:50
Here are the latest log. That time, it crashed when killing an ennemy with a new game after erasing C:\Users\YourName\Documents\Battle Brothers folder.
[log.zip](https://github.com/NgGH707/NgGH-Magic-Origins-Mod/files/8009378/log.zip)

**Comment by NgGH707** [comment] 2022-02-06 03:51
You are using an old version of legends. Please update your legends mod with the latest test build in BB Legends Mod discord server

**Closed** 2022-02-06 03:52 UTC

**Comment by Vortal4** [comment] 2022-02-06 03:57
Work perfectly fine now. I was not aware they were not updating on nexus anymore like you mod.
Thanks for the help.
